### PR TITLE
add resolved feature 

### PR DESCRIPTION
**Pull request by ruiminggu**
I create a new field for new topics with a boolean indicating whether or not the topic has been resolved. I changed the file src/topics/create.js. I spent a long time finding the correct file to fix the UI and I added a button for resolving on the topic page. 
Screen Shot 2023-09-26 at 5 36 14 PM

Issue: #10 

There are more changes that need to be done on toggling the resolved feature etc.

### CODE REVIEW

**Comment by Noor-5** [comment]
I don't think we should be adding a new topic to the resolved sorted set on create

**Comment by gonzalezjo** [comment]
I made this suggestion but it doesn't show. Weird.

**Comment by ruiminggu** [comment]
> I don't think we should be adding a new topic to the resolved sorted set on create

**Comment by Noor-5** [comment]
we need to add a field to topics/data.js for the resolved status.
I think because this is non-relational , there may not be a schema. But not sure.

**Comment by gonzalezjo** [comment]
See related references. This was merged, just outside this PR.

**Pull request closed without merging**
